services:
  postgres:
    image: "postgres:17-alpine"
    environment:
      POSTGRES_PASSWORD: article-password
      POSTGRES_USER: article-user
      POSTGRES_DB: article
    ports:
      - "5432:5432"
    volumes:
      - ../pgdata:/var/lib/postgresql/data # Map pgdata folder to PostgreSQL data directory

  article-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=article-user
      - DB_PASSWORD=article-password
      - DB_NAME=article
    depends_on:
      - postgres

volumes:
  postgres_data:
